### ISSUE TITLE
Unable to override config files in derived image

### ISSUE THREAD

**Issue by jannielsen** [linuxserver/docker-oscam#15]
Hi, I'm trying to create my own image inherited from your and add my custom config files (oscam.server, oscam.user, oscam.config). 
My first version of Dockerfile was:

```
FROM linuxserver/oscam
COPY ./config /config/oscam
```
but when I run the image then my config files was not inside.

So I changed my Dockerfile - I created volume /config (the same volume already exists in your image)´

```
FROM linuxserver/oscam
COPY ./config /config/oscam

VOLUME /config
```

Now my config files s was copied into image, but only if I haven't mapped the volume to host folder. 
When I tried to map the volume to host folder then my configs disappeared again.

I checked the documentation and I think that problem is that you are creating volume /config inside the Dockerfile.

>https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes
>Changing the volume from within the Dockerfile: If any build steps change the data within the volume after it has been declared, those changes will be discarded

The solution can be that you remove the line `VOLUME /config` and if user want to have such a volume, he can create as you suggest, ie. with parametr -v in docker command or by specifing volume section in docker-compose.

**Comment by thelamer** [comment]
Why not just mount up your config directory to a folder that has these files. 

In any case if you are making your own images I do not see any reason we would change ours to suit your needs.

**Comment by jannielsen** [comment]
The reason is simple - because it complicates image deployment.
My design allows to create an image that already contains the necessary configuration and it can be very easy deployed to different environments, which is also one of the docker tasks. In addition, nothing will change for users who deploys the container according to your instructions.

But as I read the second sentence I can see there is no way to make any change in that issue.

**Comment by thelamer** [comment]
No I get it, and I do not want you to be discouraged by the instant closeout. I just happened to be watching our github feed as I have a bunch of builds pumping through right now. 

You need to see the whole picture in that making this change would stylistically need to be made across 400+ Dockerfiles spanning our entire catalog. 

The actual reason to have the volumes in the dockerfile along with the port exposes is an in code documentation measure, someone should be able to derive a basic running example from just inspecting the local image and seeing these. 
I do not fully agree with it either as it creates docker volumes on end users systems when they chose not to bind mount the folders we define, but we are a large organization with many , many repos and a balanced system of making decisions like this. 

This specific issues has been discussed and we will not be ripping them out as far as I know.

**Comment by jannielsen** [comment]
Rogger that, it make sense.
Thank you for clarification, so we have to wait to docker when they will implement something like UNVOLUME :) (https://github.com/moby/moby/issues/3465)

**Comment by tobbenb** [comment]
You can also do it the way we do, add the files to a defaults folder, then use a script in cont-init.d that copies the files to /config on container start.
We already do that for oscam.conf.

Is all you want to add the config files?

**Comment by jannielsen** [comment]
@tobbenb, it's the way I will go.  Thank you very much.
