### ISSUE TITLE
gid of group dialout can't access device ttyUSB0

### ISSUE THREAD

**Issue by skalnet** [linuxserver/docker-oscam#21]
## Expected Behavior
passing --device /dev/ttyUSB0:/dev/ttyUSB0 should let me use my local card in my card reader.
Running oscam on the host accessing ttyUSB0 works.

## Current Behavior
oscam can't access device and throws an Error:

(reader) Reader-0 [mouse] ERROR: Opening device /dev/ttyUSB0 (errno=13 Permission denied)
(reader) Reader-0 [mouse] Cannot open device: /dev/ttyUSB0

Actually patching the Dockerfile like this get's rid of the problem. Don't know why you changed gid of dialout in the first place.
` - groupmod -g 16 dialout`    
 `- usermod -a -G 16 abc`   
 `+ usermod -a -G dialout abc` 

## Steps to Reproduce
1. Attach reader with card to usb 
2. verify that reader is actually ttyUSB0
3. pass reader to oscam container
4. get error

## Environment
**OS:**      Debian Stretch
**CPU architecture:** x86_64
**How docker service was installed:**      apt repo

## Command used to create docker container (run/create/compose/screenshot)
docker create \
  --name=oscam-local \
  -e PUID=1002 \
  -e PGID=100 \
  -e TZ=Europe/London \
  -p 8888:8888 \
  -p 9000:9000 \
  -v ~/docker/oscam/:/config \
  -v ~/docker/oscam-tmp/:/tmp \
  --net=macvlan \
  --ip=192.168.178.19 \
  --device /dev/ttyUSB0:/dev/ttyUSB0 \
  --hostname oscam \
  --restart unless-stopped \
  linuxserver/oscam

## Docker logs
[oscam_docker.log](https://github.com/linuxserver/docker-oscam/files/3935988/oscam_docker.log)

**Comment by tobbenb** [comment]
This is dependent on the host os. Changing it the way it works for you will break it for others. You can do the change locally using the blog entry Customizing our containers on linuxserver.io until I find a better way to handle the perms. We do use a better method for dvb cards and gpu in other containers that I might be able to use in oscam also.
I'll leave this open until it's implemented so I don't forget it.

**Comment by enny1170** [comment]
I'm run into the same problem. I'm try to use a smargo reader on /dev/bus/usb/002/006. An got a Message 'libusb_open error LIBUSB_ERROR_ACCESS : the user has insufficient permissions'.
Also change the dockerfile and rebuild. 
Maybe someone provide a better solution.

**Comment by bernhardberger** [comment]
Having the same permission problem on an Ubuntu 19.04 server.. how do I get rid of this?

**Comment by tobbenb** [comment]
Try changing the gid of the dialout group using the `groupmod -g 16 dialout` command. 
Check what it is in Ubuntu and then change 16 to the correct number.

**Comment by bernhardberger** [comment]
Just for documentation's sake (docker-compose v2): 
```yaml
group_add:
   - dialout
```

**Comment by bernhardberger** [comment]
> This is dependent on the host os. Changing it the way it works for you will break it for others. You can do the change locally using the blog entry Customizing our containers on linuxserver.io until I find a better way to handle the perms. We do use a better method for dvb cards and gpu in other containers that I might be able to use in oscam also.
> I'll leave this open until it's implemented so I don't forget it.

This issue still persists. I've missed dozens of recordings as right now I have to manually do a chmod 777 on /dev/ttyUSB* and restart the oscam container after every single reboot of the host..

Is there any solution in sight?

**Comment by SmoothMC** [comment]
my solution is to set PGID to 20 (PGID=20) because 20 is the group dialout on my debian 10 Server

salute ;)

**Comment by honeyx** [comment]
> my solution is to set PGID to 20 (PGID=20) because 20 is the group dialout on my debian 10 Server
> 
> salute ;)

This worked for me with Rasbian on a PI. Thanks

**Comment by honeyx** [comment]
Oh well I have to add changing the PGID worked so far but just temporaly. Everytime I restarted the docker container or did a restart within Oscam or just restarted the Server, Oscam got messed up and reported every few secounds reader status Ok and a few further secounds later NEEDINIT. This repeated continiuously. Had to delete the container and build a new one. Then it worked again till i restarted Oscam, the container or the system. Finally compiled and installed Oscam natively and now it works as expected.

**Comment by tobbenb** [comment]
I thought I had this fixed, but looks like I haven't pushed the fix and might have deleted the repo I worked on locally. It's just a modification of the code we use to set the group automatically for GPU/DVB devices so shouldn't be too hard to do.

**Comment by DJAlPee** [comment]
> I thought I had this fixed, but looks like I haven't pushed the fix and might have deleted the repo I worked on locally. It's just a modification of the code we use to set the group automatically for GPU/DVB devices so shouldn't be too hard to do.

Maybe one month is too short for the github-actions bot to mark issues as "stale" 😉 
Would be great, of you could restore/recreate your work 😃

**Comment by bernhardberger** [comment]
Bit of a bummer that this isn't planned. Wasn't there already a PR to address this? 2 years later and it's still a pain and I still regularly miss recordings after a power outage when I'm not around to do a chmod after boot :-/
