### ISSUE TITLE
how to active oscam web utf8 function?

### ISSUE THREAD

**Issue by bigdeer** [linuxserver/docker-oscam#23]
How to Open oscam web utf8 support?think you

**Comment by barzog** [comment]
It seems that for that oscam should be started with -u flag in container:
 -u, --utf8              | Enable WebIf support for UTF-8 charset.

**Comment by barzog** [comment]
Checked. Yes, after this change in /etc/services.d/oscam/run
        s6-setuidgid abc /usr/bin/oscam **-u** -c /config/oscam

UTF-8 is supported.

**Comment by tobbenb** [comment]
Somehow I have missed this issue. I'll add it when I get some time. If I forget it, please ping me.

**Comment by barzog** [comment]
Any news on that?
