### ISSUE TITLE
oscam rebase to alpine 3.13

### ISSUE THREAD

**Issue by barzog** [linuxserver/docker-oscam#29]
Alpine 3.11 is quite old. So here's new diff with rebase to 3.13.
Also fixes https://github.com/linuxserver/docker-oscam/issues/28 
https://github.com/linuxserver/docker-oscam/issues/23

[docker-oscam.diff.txt](https://github.com/linuxserver/docker-oscam/files/6095497/docker-oscam.diff.txt)

btw - it would be better that UTF8 is activated based on ENV variable (e.g. if USE_UTF_8=1 is passed - start with -u, if not - back to default latin1)

**Comment by aptalca** [comment]
Did you build and test locally? Iirc it didn't work properly in 3.12 and that's why it was held back

**Comment by barzog** [comment]
Yes. But only with newcamd reader over internet.
2021/03/06 17:16:09 00000000 s     (main) System name    = Linux
2021/03/06 17:16:09 00000000 s     (main) Host name      = oscam
2021/03/06 17:16:09 00000000 s     (main) Release        = 5.11.2-arch1-1
2021/03/06 17:16:09 00000000 s     (main) Version        = #1 SMP PREEMPT Fri, 26 Feb 2021 18:26:41 +0000
2021/03/06 17:16:09 00000000 s     (main) Machine        = x86_64
2021/03/06 17:16:09 00000000 s     (main) creating pidfile /tmp/.oscam/oscam.pid with pid 282
2021/03/06 17:16:09 00000000 s     (main) signal handling initialized
2021/03/06 17:16:09 00000000 s   (config) 2 provid's loaded
2021/03/06 17:16:09 00000000 s   (config) 38 service-id's loaded in 0 ms
2021/03/06 17:16:09 00000000 s   (reader) XXX [newcamd] creating thread for device XXXX
2021/03/06 17:16:09 0062BED9 p  (newcamd) proxy XXXX:XXXX newcamd525 (fd=0)
2021/03/06 17:16:09 00000000 s     (main) waiting for local card init
2021/03/06 17:16:09 0062BED9 p   (reader) XXX [newcamd] proxy initialized, server XXX:XXX
2021/03/06 17:16:09 701DDF09 h    (webif) webif: decompressed 185200 bytes back into 487488 bytes
2021/03/06 17:16:09 701DDF09 h    (webif) HTTP Server running. ip=0.0.0.0 port=8888
2021/03/06 17:16:09 00000000 s     (main) init for all local cards done
2021/03/06 17:16:09 00000000 s (emmcache) loading emmcache disabled since no reader is using it!
2021/03/06 17:16:09 00000000 s (emmcache) loading emmstats disabled since no reader is using it!
2021/03/06 17:16:09 00000000 s (anticasc) anti cascading disabled
2021/03/06 17:16:09 00000000 s     (gbox) local gbox failed init
2021/03/06 17:16:09 4A4AACE0 c   (client) plain dvbapi-client granted (anonymous, au=off)
2021/03/06 17:16:09 4A4AACE0 c   (dvbapi) dvbapi channelcache loaded from /config/oscam/oscam.ccache
2021/03/06 17:16:09 4A4AACE0 c   (dvbapi) Using TCP listen socket, API forced to DVBAPIv3 (0), userconfig boxtype: 11
2021/03/06 17:17:05 4A4AACE0 c   (dvbapi) Client connected: 'Tvheadend 4.3-1940~gfe0e5f1f9' (protocol version = 2)
2021/03/06 17:25:05 4A4AACE0 c   (dvbapi) Demuxer 0 ecmpid 0 CAID: --skip--
2021/03/06 17:25:05 4A4AACE0 c   (dvbapi) Demuxer 0 ecmpid 1 CAID: --skip--
2021/03/06 17:25:05 4A4AACE0 c   (dvbapi) Demuxer 0 ecmpid 2 CAID: --skip--
2021/03/06 17:25:05 4A4AACE0 c   (dvbapi) Demuxer 0 ecmpid 3 CAID: --skip--
2021/03/06 17:25:05 4A4AACE0 c   (dvbapi) Demuxer 0 found 4 ECM pids and 2 STREAM pids in CA PMT
2021/03/06 17:25:05 4A4AACE0 c   (dvbapi) Demuxer 0 trying to descramble PID 0 CAID --skip--
2021/03/06 17:25:06 0062BED9 p   (reader) --skip--: resolved ip=--skip--
2021/03/06 17:25:06 0062BED9 p   (reader) --skip-- [newcamd] connecting to --skip--
2021/03/06 17:25:07 0062BED9 p  (newcamd) Newcamd Server: --skip--
2021/03/06 17:25:07 0062BED9 p  (newcamd) CAID: --skip--
2021/03/06 17:25:07 0062BED9 p  (newcamd) Provider ID: --skip--
2021/03/06 17:25:07 0062BED9 p  (newcamd) Provider ID: --skip--
2021/03/06 17:25:07 0062BED9 p  (newcamd) Provider ID: --skip--
2021/03/06 17:25:08 4A4AACE0 c      (ecm) anonymous (--skip--): timeout (2000 ms) by --skip--
2021/03/06 17:25:08 4A4AACE0 c      (ecm) anonymous (--skip--): found (885 ms) by --skip--

**Comment by barzog** [comment]
Modified patch. Now UTF8 support is configured via ENV variable USE_UTF8. If not empty - start with UTF. If not present or empty - start without UTF.

Also I would suggest to modify pccard daemon startup file - if no USB devices is mounted there is no sense in it.
[docker-oscam.diff.txt](https://github.com/linuxserver/docker-oscam/files/6128853/docker-oscam.diff.txt)

**Comment by barzog** [comment]
Any news on that?

**Comment by tobbenb** [comment]
Feel free to make a PR.
