### ISSUE TITLE
IPV6 Support

### ISSUE THREAD

**Issue by DeBaschdi** [linuxserver/docker-oscam#32]
Hi, can u build Oscam with ipv6 support ?
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

**Comment by tobbenb** [comment]
Earlier ipv6 didn't play nice with docker, but I'll check and see if it has changed lately.

**Comment by DeBaschdi** [comment]
You're absolutely right, 
at least with Unraid 6.10+ it finally works almost ootb. 

For 2 days I personally only have ipv6 available with German fiber optics to the outside.
Would be great,  if you could build oscam with ipv6.

Just uncomment this Line 
https://github.com/linuxserver/docker-oscam/blob/e19c0ef98ecd8a261a5b5f76ff8d9e1c3a149e56/Dockerfile#L46

**Comment by tobbenb** [comment]
If I remember correctly, newcamd didn't work as long as ipv6 was compiled. If that is still the issue it's a no go.
