### ISSUE TITLE
Smargo Cardreader

### ISSUE THREAD

**Issue by muximde** [linuxserver/docker-oscam#40]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hello can build an oscam with the option "libusb" please, so my Smartreader will work (Smargo)

Thank you

### Reason for change

for example

I can use in "oscam.server"

protocol                      = smartreader
device                        = Serial:Reader 6A7B4C8

The Smartreader is located over the Serial Nr. 

for this is needed befor build oscam to select the feature "libusb"

Thank you in advance
Nico

### Proposed code change

Select "libusb"

**Comment by muximde** [comment]
Hello

perhaps this helps
it was in the log  


"01:12:02 4596500E r   (reader) SRG_Swiss [smartreader] Libusb init error : -99"

**Comment by j0nnymoe** [comment]
This is already enabled as we enable all options for oscam.
https://github.com/linuxserver/docker-oscam/blob/1c756a05f978f507c0ea33b586e8c93603c716ad/Dockerfile#L34

**Comment by muximde** [comment]
ok, thank you
hmm.. perhaps in Unraid is missing the "libusb driver"

**Comment by muximde** [comment]
i made my oscam with simple build

I select:
Argolis Smargo Smartreader

**Comment by muximde** [comment]
I mean for my last Oscam, but i dont kow were your osam is located for testing with my options
thank you

**Comment by muximde** [comment]
sorry for my disturb.

i found this, here is the Smargo listet:

https://build.alpinelinux.org/buildlogs/build-edge-x86_64/community/oscam/oscam-1.20_svn20201119-r4.log

Excuse me

**Comment by muximde** [comment]
Hello again

perhaps there are no enough rights to start Libusb or there is missing

see the Log:

"10:07:04 223D5B6A r   (reader) hd+2 [smartreader] Libusb init error : -99
10:07:04 223D5B6A r   (reader) hd+2 [smartreader] Cannot open device: Serial:Reader 443913F
10:07:06 223D5B6A r   (reader) hd+2 [smartreader] Libusb init error : -99
10:07:06 223D5B6A r   (reader) hd+2 [smartreader] Cannot open device: Serial:Reader 443913F
10:07:08 223D5B6A r   (reader) hd+2 [smartreader] Libusb init error : -99
10:07:08 223D5B6A r   (reader) hd+2 [smartreader] Cannot open device: Serial:Reader 443913F
10:07:10 223D5B6A r   (reader) hd+2 [smartreader] Libusb init error : -99
10:07:10 223D5B6A r   (reader) hd+2 [smartreader] Cannot open device: Serial:Reader 443913F
10:07:12 223D5B6A r   (reader) hd+2 [smartreader] Libusb init error : -99
10:07:12 223D5B6A r   (reader) hd+2 [smartreader] Cannot open device: Serial:Reader 443913F
10:07:14 223D5B6A r   (reader) hd+2 [smartreader] Libusb init error : -99
10:07:14 223D5B6A r   (reader) hd+2 [smartreader] Cannot open device: Serial:Reader 443913F
10:07:16 223D5B6A r   (reader) hd+2 [smartreader] Libusb init error : -99
10:07:16 223D5B6A r   (reader) hd+2 [smartreader] Cannot open device: Serial:Reader 443913F
10:07:18 223D5B6A r   (reader) hd+2 [smartreader] Libusb init error : -99
10:07:18 223D5B6A r   (reader) hd+2 [smartreader] Cannot open device: Serial:Reader 443913F
10:07:20 223D5B6A r   (reader) hd+2 [smartreader] Libusb init error : -99
10:07:20 223D5B6A r   (reader) hd+2 [smartreader] Cannot open device: Serial:Reader 443913F
10:07:22 223D5B6A r   (reader) hd+2 [smartreader] Libusb init error : -99
10:07:22 223D5B6A r   (reader) hd+2 [smartreader] Cannot open device: Serial:Reader 443913F
10:07:22 00000000 s     (main) init for all local cards done

thank you
